// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoVhIrL8EOUS2H0Oju6tIXI1rF6WVkHw',
    appId: '1:505346907710:web:5f3830829a0f0d01843b6f',
    messagingSenderId: '505346907710',
    projectId: 'fir-setup-3425b',
    authDomain: 'fir-setup-3425b.firebaseapp.com',
    storageBucket: 'fir-setup-3425b.firebasestorage.app',
    measurementId: 'G-DGXER56VV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJ0yQ4rEGI-Fy6lwM0grbSOPqDjfkhOY',
    appId: '1:637861580830:android:b793ea51d977bfaa085e0f',
    messagingSenderId: '637861580830',
    projectId: 'smartable-42ed4',
    storageBucket: 'smartable-42ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOTkaPkiRjJ-4MNHqZRf6scTLUvySPuo',
    appId: '1:637861580830:ios:a51a981dd7c99346085e0f',
    messagingSenderId: '637861580830',
    projectId: 'smartable-42ed4',
    storageBucket: 'smartable-42ed4.firebasestorage.app',
    iosClientId: '637861580830-2s525l6urnku2cle4nfa2relktj138c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartable',
  );

}